AplicacaoMedicina/Models/Agenda.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;


namespace AplicacaoMedicina.Models
{
    public class Agenda
    {
        [Key]
        public int ID_Agenda { get; set; }

        [Required]
        [DataType(DataType.Date)]
        [DisplayFormat(ApplyFormatInEditMode = true, DataFormatString = "{0:dd/MM/yyyy HH:mm}")]
        public DateTime Data_Agenda { get; set; }

        public string DSeman_Agenda { get; set; }

        [Required]
        [ForeignKey("MedicoConsultorio")]
        public int ID_MediConsul { get; set; }

        [Required]
        public bool ativo { get; set; }

        public virtual MedicoConsultorio MedicoConsultorio { get; set; }
    }
}

AplicacaoMedicina/Controllers/AgendaController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using AplicacaoMedicina.DataContexts;
using AplicacaoMedicina.Models;

namespace AplicacaoMedicina.Controllers
{
    public class AgendaController : Controller
    {
        private DrMedContext db = new DrMedContext();

        // GET: Agenda
        [CustomAuthorization(LoginPage = "~/UsuarioConsultorios/Login", Roles = "Consultorio")]
        public ActionResult Index(int id, string redirect)
        {
            var medico = db.MedicoConsultorios.Find(id);

            if (medico == null) {
                return HttpNotFound();
            }

            ViewBag.ID_MediConsul = id;
            ViewBag.NomeMedico = medico.Medico.Nome_Medi;

            ViewBag.Redirect = redirect;
            //ViewBag.ConsultorioID = Int32.Parse(Request.Cookies["ConsultorioID"].Value);
            return View();
        }

        public JsonResult GetEvents(int? ID_MediConsul)
        {
            var agendas = db.Agendas.Where(x => x.ID_MediConsul == ID_MediConsul);

            var events = new List<object>();
            DateTime Data;
            string startDate;
            string endDate;

            foreach (var x in agendas) {

                switch(x.DSeman_Agenda){

                case "Segunda":
                        Data = DateTime.Parse("2017-07-10"+ " " + x.Data_Agenda.ToString("HH:mm"));
                        startDate = Data.ToString("yyyy-MM-ddTHH\\:mm\\:ss.fffffffzzz");
                        endDate = Data.AddMinutes(30).ToString("yyyy-MM-ddTHH\\:mm\\:ss.fffffffzzz");

                        events.Add(new { allday = "", title = "Consulta", /*id = x.ID_Agenda,*/ start = startDate, end = endDate,  overlap = false, durationEditable = false });
                        break;
                case "Terca":
                        Data = DateTime.Parse("2017-07-11" + " " + x.Data_Agenda.ToString("HH:mm"));
                        startDate = Data.ToString("yyyy-MM-ddTHH\\:mm\\:ss.fffffffzzz");
                        endDate = Data.AddMinutes(30).ToString("yyyy-MM-ddTHH\\:mm\\:ss.fffffffzzz");

                        events.Add(new { allday = "", title = "Consulta", /*id = x.ID_Agenda,*/ start = startDate, end = endDate,  overlap = false, durationEditable = false });

                        break;
                case "Quarta":
                        Data = DateTime.Parse("2017-07-12" + " " + x.Data_Agenda.ToString("HH:mm"));
                        startDate = Data.ToString("yyyy-MM-ddTHH\\:mm\\:ss.fffffffzzz");
                        endDate = Data.AddMinutes(30).ToString("yyyy-MM-ddTHH\\:mm\\:ss.fffffffzzz");

                        events.Add(new { allday = "", title = "Consulta", /*id = x.ID_Agenda,*/ start = startDate, end = endDate,  overlap = false, durationEditable = false });

                        break;
                case "Quinta":
                        Data = DateTime.Parse("2017-07-13" + " " + x.Data_Agenda.ToString("HH:mm"));
                        startDate = Data.ToString("yyyy-MM-ddTHH\\:mm\\:ss.fffffffzzz");
                        endDate = Data.AddMinutes(30).ToString("yyyy-MM-ddTHH\\:mm\\:ss.fffffffzzz");

                        events.Add(new { allday = "", title = "Consulta", /*id = x.ID_Agenda,*/ start = startDate, end = endDate,  overlap = false, durationEditable = false });

                        break;
                case "Sexta":
                        Data = DateTime.Parse("2017-07-14" + " " + x.Data_Agenda.ToString("HH:mm"));
                        startDate = Data.ToString("yyyy-MM-ddTHH\\:mm\\:ss.fffffffzzz");
                        endDate = Data.AddMinutes(30).ToString("yyyy-MM-ddTHH\\:mm\\:ss.fffffffzzz");

                        events.Add(new { allday = "", title = "Consulta", /*id = x.ID_Agenda,*/ start = startDate, end = endDate,  overlap = false, durationEditable = false });

                        break;
                case "Sabado":
                        Data = DateTime.Parse("2017-07-15" + " " + x.Data_Agenda.ToString("HH:mm"));
                        startDate = Data.ToString("yyyy-MM-ddTHH\\:mm\\:ss.fffffffzzz");
                        endDate = Data.AddMinutes(30).ToString("yyyy-MM-ddTHH\\:mm\\:ss.fffffffzzz");

                        events.Add(new { allday = "", title = "Consulta", /*id = x.ID_Agenda,*/ start = startDate, end = endDate,  overlap = false, durationEditable = false });

                        break;
                default:
                        Data = DateTime.Parse("2017-07-09" + " " + x.Data_Agenda.ToString("HH:mm"));
                        startDate = Data.ToString("yyyy-MM-ddTHH\\:mm\\:ss.fffffffzzz");
                        endDate = Data.AddMinutes(30).ToString("yyyy-MM-ddTHH\\:mm\\:ss.fffffffzzz");

                        events.Add(new { allday = "", title = "Consulta", /*id = x.ID_Agenda,*/ start = startDate, end = endDate,  overlap = false, durationEditable = false });

                        break;
                }
                                                           
            }

            return Json(events, JsonRequestBehavior.AllowGet);

        }

        // POST: Agenda/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.

        [HttpPost]
        [ValidateAntiForgeryToken]
        [CustomAuthorization(LoginPage = "~/UsuarioConsultorios/Login", Roles = "Consultorio")]
        public JsonResult Create(List<FCalendar> events, int ID_MediConsul, string Redirect)
        {

            db.Agendas.RemoveRange(db.Agendas.Where(x => x.ID_MediConsul == ID_MediConsul));
                       
            string dayOfWeek;
                       
            foreach (var item in events)
            { 
                Agenda agenda = new Agenda();
                agenda.ID_MediConsul = ID_MediConsul;
                agenda.Data_Agenda = DateTime.Parse(item.start.Substring(0,19));

                dayOfWeek = item.start.Substring(0,10);

                switch (dayOfWeek)
                {
                    case "2017-07-10":
                        agenda.DSeman_Agenda = "Segunda";
                        break;
                    case "2017-07-11":
                        agenda.DSeman_Agenda = "Terca";
                        break;
                    case "2017-07-12":
                        agenda.DSeman_Agenda = "Quarta";
                        break;
                    case "2017-07-13":
                        agenda.DSeman_Agenda = "Quinta";
                        break;
                    case "2017-07-14":
                        agenda.DSeman_Agenda = "Sexta";
                        break;
                    case "2017-07-15":
                        agenda.DSeman_Agenda = "Sabado";
                        break;
                    default:
                        agenda.DSeman_Agenda = "Domingo";
                        break;
                }

                agenda.ativo = true;

                db.Agendas.Add(agenda);
                db.SaveChanges();
            }

            if (Redirect == "Save")  {
                return Json(new { success = true, result = "Save" }, JsonRequestBehavior.AllowGet);
            }

            if (Redirect == "MultipleSave") {
                return Json(new { success = true, result = "MultipleSave" }, JsonRequestBehavior.AllowGet);
            }


            var teste = db.Agendas.Where(x => x.ID_MediConsul == ID_MediConsul);
        
            return Json(new { success = true, result = "Conclusion" }, JsonRequestBehavior.AllowGet);

           // return Json(new { teste, events }, JsonRequestBehavior.AllowGet);


        }

       
    }
}

AplicacaoMedicina/Views/Agenda/Delete.cshtml
@model AplicacaoMedicina.Models.Agenda

@{
    ViewBag.Title = "Delete";
    Layout = "~/Views/Shared/_LayoutMedico.cshtml";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Agenda</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.MedicoConsultorio.ID_MediConsu)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.MedicoConsultorio.ID_MediConsu)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Data_Agenda)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Data_Agenda)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.DSeman_Agenda)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.DSeman_Agenda)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.ativo)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.ativo)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

AplicacaoMedicina/Views/Agenda/Details.cshtml
@model AplicacaoMedicina.Models.Agenda

@{
    ViewBag.Title = "Details";
    Layout = "~/Views/Shared/_LayoutMedico.cshtml";
}

<h2>Details</h2>

<div>
    <h4>Agenda</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.MedicoConsultorio.ID_MediConsu)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.MedicoConsultorio.ID_MediConsu)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Data_Agenda)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Data_Agenda)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.DSeman_Agenda)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.DSeman_Agenda)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.ativo)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.ativo)
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Edit", "Edit", new { id = Model.ID_Agenda }) |
    @Html.ActionLink("Back to List", "Index")
</p>

AplicacaoMedicina/Views/Agenda/Edit.cshtml
@model AplicacaoMedicina.Models.Agenda

@{
    ViewBag.Title = "Edit";
    Layout = "~/Views/Shared/_LayoutMedico.cshtml";
}

<h2>Edit</h2>

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Agenda</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.ID_Agenda)

        <div class="form-group">
            @Html.LabelFor(model => model.Data_Agenda, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Data_Agenda, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Data_Agenda, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.DSeman_Agenda, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.DSeman_Agenda, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.DSeman_Agenda, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.ID_MediConsul, "ID_MediConsul", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("ID_MediConsul", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.ID_MediConsul, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.ativo, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                <div class="checkbox">
                    @Html.EditorFor(model => model.ativo)
                    @Html.ValidationMessageFor(model => model.ativo, "", new { @class = "text-danger" })
                </div>
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

AplicacaoMedicina/Views/Agenda/Index.cshtml
@{
    Layout = "~/Views/Shared/_LayoutMedico.cshtml";
}

<div class="row">
    <div class="col-md-12">
        <div class="card">
            <div class="card-header" data-background-color="purple">
                <h4 class="title">Agenda - @ViewBag.NomeMedico</h4>
                <p class="category">Preencha os Dados</p>
            </div>
            <div class="card-content">

                @using (Html.BeginForm("Create", "Agenda", FormMethod.Post, new { id = "cadastrar" }))
                {
                    @Html.AntiForgeryToken()

                    <input type="hidden" name="ID_MediConsul" id="ID_MediConsul" value="@ViewBag.ID_MediConsul" />
                    <input type="hidden" name="ID_MediConsul" id="Redirect" value="@ViewBag.Redirect" />

                    <div id="calendar"></div>
                    <div class="form-horizontal">
                        @Html.ValidationSummary(true, "", new { @class = "text-danger" })


                        <div class="form-group">
                            <div class="col-md-offset-2 col-md-10">
                                                                
                                    <button id="submit" type="submit" value="Save" class="btn btn-primary pull-right">Atualizar Agenda</button>
                                
                            </div>
                        </div>
                    </div>
                }
            </div>
        </div>
    </div>
</div>