AplicacaoMedicina/Models/AreaConsultorio.cs
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace AplicacaoMedicina.Models
{
    public class AreaConsultorio
    {
        [Key]
        public int ID_Area { get; set; }

        [Required]
        [MaxLength(45)]
        public string Nome_Area { get; set; }

        [ForeignKey("Consultorio")]
        public int ID_Consu { get; set; }

        public virtual Consultorio Consultorio { get; set; }
    }
}

AplicacaoMedicina/Controllers/AreaConsultoriosController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using AplicacaoMedicina.DataContexts;
using AplicacaoMedicina.Models;

namespace AplicacaoMedicina.Controllers
{
    public class AreaConsultoriosController : Controller
    {
        private DrMedContext db = new DrMedContext();

        // GET: AreaConsultorios
       /* public ActionResult Index()
        {
            var areaConsultorios = db.AreaConsultorios.Include(a => a.Consultorio);
            return View(areaConsultorios.ToList());
        }*/

        // GET: AreaConsultorios/Details/5
    /*    public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            AreaConsultorio areaConsultorio = db.AreaConsultorios.Find(id);
            if (areaConsultorio == null)
            {
                return HttpNotFound();
            }
            return View(areaConsultorio);
        }*/

        // GET: AreaConsultorios/Create
        public ActionResult Create()
        {           
            return View();
        }

        // POST: AreaConsultorios/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public JsonResult Create([Bind(Include = "ID_Area,Nome_Area,ID_Consu")] AreaConsultorio areaConsultorio)
        {
            areaConsultorio.ID_Consu = Int32.Parse(Request.Cookies["ConsultorioID"].Value);

            ModelState.Clear();
            TryUpdateModel(areaConsultorio);

            if (ModelState.IsValid)
            {
                db.AreaConsultorios.Add(areaConsultorio);
                db.SaveChanges();
                return Json(new { success = true, message = areaConsultorio }, JsonRequestBehavior.AllowGet);
            }

            return Json(new { success = false }, JsonRequestBehavior.AllowGet);
        }

        // GET: AreaConsultorios/Edit/5
     /*   public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            AreaConsultorio areaConsultorio = db.AreaConsultorios.Find(id);
            if (areaConsultorio == null)
            {
                return HttpNotFound();
            }
            ViewBag.ID_Consu = new SelectList(db.Consultorios, "ID_Consu", "Nome_Consu", areaConsultorio.ID_Consu);
            return View(areaConsultorio);
        }*/

        // POST: AreaConsultorios/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
 /*       [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "ID_Area,Nome_Area,ID_Consu")] AreaConsultorio areaConsultorio)
        {
            if (ModelState.IsValid)
            {
                db.Entry(areaConsultorio).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.ID_Consu = new SelectList(db.Consultorios, "ID_Consu", "Nome_Consu", areaConsultorio.ID_Consu);
            return View(areaConsultorio);
        }
        */
        // GET: AreaConsultorios/Delete/5
      /*  public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            AreaConsultorio areaConsultorio = db.AreaConsultorios.Find(id);
            if (areaConsultorio == null)
            {
                return HttpNotFound();
            }
            return View(areaConsultorio);
        }*/

        // POST: AreaConsultorios/Delete/5
     /*   [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            AreaConsultorio areaConsultorio = db.AreaConsultorios.Find(id);
            db.AreaConsultorios.Remove(areaConsultorio);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }*/
    }
}

AplicacaoMedicina/Views/AreaConsultorios/Create.cshtml
@model AplicacaoMedicina.Models.AreaConsultorio

@{
    Layout= "";
}

<div class="modal-header">
    <h4><b>Nova Área</b></h4>
</div>
<div class="modal-body">
    <div class="row">
        <div class="col-md-12">
            <dl>
                @using (Html.BeginForm("Create", "AreaConsultorios", FormMethod.Post, new { id = "edita" }))
                {
                    @Html.AntiForgeryToken()

                    <div class="form-horizontal">
                        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
                        <div class="form-group">
                            @Html.LabelFor(model => model.Nome_Area, htmlAttributes: new { @class = "control-label col-md-2" })
                            <div class="col-md-10">
                                @Html.EditorFor(model => model.Nome_Area, new { htmlAttributes = new { @class = "form-control" } })
                                @Html.ValidationMessageFor(model => model.Nome_Area, "", new { @class = "text-danger" })
                            </div>
                        </div>                       

                        <div class="form-group">
                            <div class="col-md-offset-2 col-md-10">
                                <button type="submit" value="Cadastrar" class="btn btn-primary pull-right">Cadastrar</button>
                            </div>
                        </div>
                    </div>
                }
            </dl>
        </div>
    </div>
</div>

<style>
    .modal-dialog{
        left: 0px;
    }
</style>

<script>
    $("#edita button").on("click", function (event) {
        event.preventDefault();

        console.log("entrou");

        var form = document.getElementById("edita");
        var data = $(form).serialize();
        var modulo = $("#edita").attr("action");

        console.log(data);

        $.ajax({
            url: modulo,
            type: 'POST',
            data: data,
            success: function (response) {
                if (response && response.success) {
                    $('#myModal').modal('toggle');
                    $('#ID_Area').append($('<option></option>')
                        .val(response.message.ID_Consu)
                        .html(response.message.Nome_Area));
                } else {
                    alert("Error");
                }
            }, error: function (x, y, err) {
                alert("Operação não efetuada");
            }
        });

    });   

</script>

AplicacaoMedicina/Views/AreaConsultorios/Delete.cshtml
@model AplicacaoMedicina.Models.AreaConsultorio

@{
    ViewBag.Title = "Delete";
    Layout = "~/Views/Shared/_LayoutMedico.cshtml";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>AreaConsultorio</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Consultorio.Nome_Consu)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Consultorio.Nome_Consu)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Nome_Area)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Nome_Area)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

AplicacaoMedicina/Views/AreaConsultorios/Details.cshtml
@model AplicacaoMedicina.Models.AreaConsultorio

@{
    ViewBag.Title = "Details";
    Layout = "~/Views/Shared/_LayoutMedico.cshtml";
}

<h2>Details</h2>

<div>
    <h4>AreaConsultorio</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Consultorio.Nome_Consu)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Consultorio.Nome_Consu)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Nome_Area)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Nome_Area)
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Edit", "Edit", new { id = Model.ID_Area }) |
    @Html.ActionLink("Back to List", "Index")
</p>

AplicacaoMedicina/Views/AreaConsultorios/Edit.cshtml
@model AplicacaoMedicina.Models.AreaConsultorio

@{
    ViewBag.Title = "Edit";
    Layout = "~/Views/Shared/_LayoutMedico.cshtml";
}

<h2>Edit</h2>

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>AreaConsultorio</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.ID_Area)

        <div class="form-group">
            @Html.LabelFor(model => model.Nome_Area, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Nome_Area, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Nome_Area, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.ID_Consu, "ID_Consu", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("ID_Consu", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.ID_Consu, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

AplicacaoMedicina/Views/AreaConsultorios/Index.cshtml
@model IEnumerable<AplicacaoMedicina.Models.AreaConsultorio>

@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_LayoutMedico.cshtml";
}

<h2>Index</h2>

<p>
    @Html.ActionLink("Create New", "Create")
</p>
<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.Consultorio.Nome_Consu)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Nome_Area)
        </th>
        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.Consultorio.Nome_Consu)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Nome_Area)
        </td>
        <td>
            @Html.ActionLink("Edit", "Edit", new { id=item.ID_Area }) |
            @Html.ActionLink("Details", "Details", new { id=item.ID_Area }) |
            @Html.ActionLink("Delete", "Delete", new { id=item.ID_Area })
        </td>
    </tr>
}

</table>